name: Deploy blog to GitHub Pages at ./blog/

on:
  push:
    branches:
      - main

jobs:
  deploy_blog:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: blog
          external_repository: sustech-cmp/sustech-cmp.github.io
