name: Deploy blog to GitHub Pages at ./blog/

on:
  push:
    branches:
      - main

jobs:
  deploy_blog:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.UPLOAD_TOKEN }}
          publish_dir: ./public
          publish_branch: main
          destination_dir: blog
          external_repository: sustech-cmp/sustech-cmp.github.io
